### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by vca007** [Davidatlarge/ggTS#2]
Hi, I have been trying to install the package to R, and used the following command: `install_github("Davidatlarge/ggTS")`
I obtained this error message: Error: Failed to install 'ggts' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)

I also tried to download the zip file manually, but then faced this issue: Warning in install.packages :
  cannot open compressed file 'ggTS-1.0.0/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection.

Are you familiar with this issue and if yes how is it best to install it? Thank you!

**Comment by markolipka** [comment]
Hi, this is not a package but rather a single useful function. The R code of the `ggTS()`-function can be found here:
https://github.com/Davidatlarge/ggTS/blob/master/ggTS_DK.R

Just copy/paste it into your own code or download the .R-file and `source()` it.
